name: CI/CD pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4 

      - name: Build Docker image
        run: docker build -t github-actions-ci-cd .
      - name: Run Docker container
        run: docker -d -p 8080:80 --name test-container github-actions-ci-cd
      
      - name: Test container 
        run: curl -f http://localhost:8080

      - name: stop container 
        run: docker stop test-container
         
